# Generated by Django 6.0.2 on 2026-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsiLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('real_life_example', models.TextField()),
                ('protocols', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-layer_number'],
            },
        ),
    ]
