# Generated by Django 6.0.2 on 2026-03-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('real_life_example', models.TextField()),
                ('protocols', models.TextField()),
            ],
            options={
                'ordering': ['-layer_number'],
            },
        ),
        migrations.DeleteModel(
            name='OsiLayer',
        ),
    ]
