# Generated by Django 6.0.2 on 2026-03-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osi', '0002_interviewquestion_layer_delete_osilayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_port', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_details', to='osi.layer')),
            ],
        ),
    ]
