# Generated by Django 5.2.9 on 2026-03-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='default_port',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
    ]
